version: '3'
services:

  elastic:
    image: elasticsearch:6.7.2
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      node.name: node
      cluster.name: elastic
      transport.host: 127.0.0.1
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:6.7.2
    ports:
      - "5601:5601"
    links:
      - elastic:elasticsearch
    environment:
      SERVER_NAME: elastic

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.12
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic:9200
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    depends_on:
      - elastic

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.12
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    environment:
      COLLECTOR_HOST_PORT: jaeger-collector:14267
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.12
    ports:
      - "16686:16686"
      - "16687:16687"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic:9200
    depends_on:
      - jaeger-agent