version: '3'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.11
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticserch:9200
    links:
      - elastic:elasticsearch

  elastic:
    image: elasticsearch:6.7.2
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      node.name: local-node
      cluster.name: local-elastic
      transport.host: 127.0.0.1

  kibana:
    image: kibana:6.7.2
    ports:
      - "5601:5601"
    links:
      - elastic:elasticsearch
    environment:
      SERVER_NAME: local-elastic